[MLU] add mlu op kernels
PaddlePaddle/PaddleCustomDevice pull request #109
Opened 2022-09-14 09:26 UTC by Ashelly1

[MLU] add mlu op kernels
* add kernel: reshape2

* add kernel: roi_align

* add kernel: scale

* add kernel: shape

* add kernel: sigmoid_cross_with_logits

* add kernel: size

* add kernel: slice

* add kernel: stack

* add kernel: tile

2022-09-14 10:08 UTC, ShawnNew requested changes
部分缩进需要检查一下

2022-09-14 10:08 UTC, ShawnNew commented on backends/mlu/kernels/size_kernel.cc
> +    int64_t size = input.numel();
reformat

2022-09-14 10:08 UTC, ShawnNew commented on backends/mlu/kernels/sigmoid_cross_with_logits_kernel.cc
> +    MLUCnnlTensorDesc x_desc(x);
reformat

2022-09-14 10:08 UTC, ShawnNew commented on backends/mlu/kernels/sigmoid_cross_with_logits_kernel.cc
> +    MLUCnnlTensorDesc x_desc(x);
reformat

2022-09-14 10:08 UTC, ShawnNew commented on backends/mlu/kernels/roi_align_kernel.cc
> +     MemCpyD2H(nullptr,
reformat

2022-09-15 12:03 UTC, Ashelly1 commented on backends/mlu/kernels/size_kernel.cc
> +    int64_t size = input.numel();
已修改

2022-09-15 12:03 UTC, Ashelly1 commented on backends/mlu/kernels/sigmoid_cross_with_logits_kernel.cc
> +    MLUCnnlTensorDesc x_desc(x);
已修改

2022-09-15 12:03 UTC, Ashelly1 commented on backends/mlu/kernels/sigmoid_cross_with_logits_kernel.cc
> +    MLUCnnlTensorDesc x_desc(x);
已修改

2022-09-15 12:03 UTC, Ashelly1 commented on backends/mlu/kernels/roi_align_kernel.cc
> +     MemCpyD2H(nullptr,
已修改

2022-09-16 07:51 UTC, ShawnNew approved these changes
👍

2022-09-16 07:54 UTC, ronny1996 approved these changes
LGTM

2022-09-16 07:55 UTC, merged