[MLU] add fused_rms and rope kernel
PaddlePaddle/PaddleCustomDevice pull request #1292
Opened 2024-06-07 09:21 UTC by PeiyuLau

2024-07-03 09:58 UTC, ShawnNew requested changes

2024-07-03 09:58 UTC, ShawnNew commented on backends/mlu/tests/unittests/test_rms_norm_op_mlu.py
> +# class TestMLURMSNormBF16(TestMLURMSNormFP32):
为什么注释？不用的话可以删除

2024-07-03 09:58 UTC, ShawnNew commented on backends/mlu/tests/unittests/test_rope_op_mlu.py
> +# class TestMLUROPEBF16(TestMLUROPEFP32):
同上

2024-07-03 09:58 UTC, ShawnNew commented on backends/mlu/plugin_ops/fused_rope_mlu.cc
> +  dev_ctx->Alloc(trans_query_out, query_tensor->dtype());
两次重复Alloc

2024-07-03 09:58 UTC, ShawnNew commented on backends/mlu/plugin_ops/fused_rope_mlu.cc
> +  (*dev_ctx).Alloc(trans_query_grad_temp, query_tensor->dtype());
两次重复Alloc

2024-07-04 07:21 UTC, PeiyuLau commented on backends/mlu/tests/unittests/test_rms_norm_op_mlu.py
> +# class TestMLURMSNormBF16(TestMLURMSNormFP32):
已删除

2024-07-04 07:22 UTC, PeiyuLau commented on backends/mlu/tests/unittests/test_rope_op_mlu.py
> +# class TestMLUROPEBF16(TestMLUROPEFP32):
已删除

2024-07-04 07:22 UTC, PeiyuLau commented on backends/mlu/plugin_ops/fused_rope_mlu.cc
> +  dev_ctx->Alloc(trans_query_out, query_tensor->dtype());
已删除

2024-07-04 07:23 UTC, PeiyuLau commented on backends/mlu/plugin_ops/fused_rope_mlu.cc
> +  (*dev_ctx).Alloc(trans_query_grad_temp, query_tensor->dtype());
已删除

2024-07-04 08:00 UTC, ShawnNew approved these changes
LGTM

2024-07-05 02:48 UTC, merged