[MLU] fix masked_select kernel
PaddlePaddle/PaddleCustomDevice pull request #369
Opened 2023-01-16 02:47 UTC by Ashelly1

fix masked_select kernel

2023-01-16 06:06 UTC, ShawnNew requested changes
把ci通过的截图贴一下

2023-01-16 06:06 UTC, ShawnNew commented on backends/mlu/kernels/masked_select_kernel.cc
> +  dev_ctx.Wait();
d2d之后的wait可不加，拿掉之后测试一下

2023-01-17 02:35 UTC, Ashelly1 commented on backends/mlu/kernels/masked_select_kernel.cc
> +  dev_ctx.Wait();
已修改

2023-01-17 02:37 UTC, Ashelly1 commented
argsot :
![image](https://user-images.githubusercontent.com/22099158/212797512-bf756f8c-d4e8-45c4-a74d-4ca1ef9fb0c8.png)

2023-01-17 02:38 UTC, Ashelly1 commented
masked_select:
![image](https://user-images.githubusercontent.com/22099158/212797678-1202fb49-5334-4f78-9470-830bed4462f8.png)

2023-01-17 02:55 UTC, ShawnNew approved these changes
👍

2023-02-01 02:27 UTC, ronny1996 approved these changes

2023-02-01 02:27 UTC, merged