[MLU-FIX] fix kernels: scale top_k tril_triu pool2d
PaddlePaddle/PaddleCustomDevice pull request #405
Opened 2023-02-13 03:32 UTC by claire199705

2023-02-13 08:37 UTC, ShawnNew requested changes

2023-02-13 08:37 UTC, ShawnNew commented on backends/mlu/kernels/pool2d_kernel.cc
> +    MLUCnnlTensorDesc* pindex_tensor_desc;
1. 这里不需要用指针，后面可以直接=过来就行
2. 另外，添加一个注释解释一下原因，增加可读性（照顾不熟悉cnnl的读者）
3. Alloc放在条件判断里面做，保证分配内存与dtype一致性

2023-02-14 03:23 UTC, claire199705 commented on backends/mlu/kernels/pool2d_kernel.cc
> +    MLUCnnlTensorDesc* pindex_tensor_desc;
3点都已修改

2023-02-14 03:24 UTC, ShawnNew approved these changes
👍

2023-02-14 03:24 UTC, merged