[MLU] fix mlu backend unittests for custom device
PaddlePaddle/PaddleCustomDevice pull request #458
Opened 2023-03-21 13:07 UTC by wufann

[MLU] fix mlu backend unittests for custom device

2023-03-21 13:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleCustomDevice?pullRequest=458) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleCustomDevice?pullRequest=458) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleCustomDevice?pullRequest=458) it.</sub>

2023-03-22 01:19 UTC, ShawnNew approved these changes
👍

2023-03-22 02:04 UTC, ShawnNew requested changes

2023-03-22 02:04 UTC, ShawnNew commented on backends/mlu/tests/unittests/test_where_op_mlu.py
> +        data = np.array([[True, False], [False, True]]).astype(np.float32)
直接删除吧

2023-03-22 02:25 UTC, wufann commented on backends/mlu/tests/unittests/test_where_op_mlu.py
> +        data = np.array([[True, False], [False, True]]).astype(np.float32)
done

2023-03-22 02:27 UTC, ShawnNew approved these changes

2023-03-22 06:19 UTC, ShawnNew approved these changes
👍

2023-03-22 06:20 UTC, merged