[MLU] add ci script
PaddlePaddle/PaddleCustomDevice pull request #477
Opened 2023-03-30 03:44 UTC by claire199705

2023-03-30 03:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleCustomDevice?pullRequest=477) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleCustomDevice?pullRequest=477) before we can accept your contribution.<br/><hr/>**tanhaojue** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleCustomDevice?pullRequest=477) it.</sub>

2023-03-30 10:03 UTC, Ivorfeng commented on backends/mlu/tools/dockerfile/build-image.sh
> +
这里传参$1~$4 
另外，docker file 本地build 过吗？

2023-03-30 11:21 UTC, claire199705 commented on backends/mlu/tools/dockerfile/build-image.sh
> +
1.传参已修改。
2.本地build过了
命令如下：bash build-image.sh
log如下：Successfully tagged registry.baidubce.com/device/paddle-mlu:cnnltoolkit3.1.2-1-cnnl1.13.2-1-gcc82

2023-03-31 01:32 UTC, ShawnNew commented on backends/mlu/tools/dockerfile/build-image.sh
> +
本地测试一下ci的脚本

2023-03-31 01:42 UTC, ShawnNew requested changes

2023-03-31 01:42 UTC, ShawnNew commented on backends/mlu/tools/dockerfile/Dockerfile.mlu.ubuntu18-x86_64-gcc82
> +# install paddlepaddle-cpu whl package
这里0.0.0是nightly的版本，先不安装在镜像中。避免由于版本不匹配造成的流水挂掉和给开发者造成的困扰。

2.5正式版发布之后再在镜像中安装发布版paddle-cpu

2023-03-31 01:42 UTC, ShawnNew commented on backends/mlu/tools/pr_ci_mlu.sh
> +    # skip paddlepaddle cpu install as mlu docker image already have cpu whl package installed
见上条评论，这里先本地编译paddle-cpu吧，开发者上传代码也需要测试一下develop的最新提交和插件之间的兼容性。

等切分支之后再修改

2023-03-31 01:42 UTC, ShawnNew commented on backends/mlu/tools/pr_ci_mlu.sh
> +    retry_time=4
retry先不要或者减少，内部要保证测例通过，随机发生的错误需要定位一下

2023-03-31 01:51 UTC, ShawnNew requested changes

2023-03-31 01:51 UTC, ShawnNew commented on backends/mlu/tools/dockerfile/build-image.sh
> +CNTOOLKIT_VERSION=${1:-3.1.2-1} # default 3.1.2-1
修改一下ctr2.8.1的版本

2023-03-31 02:00 UTC, ShawnNew requested changes

2023-03-31 02:00 UTC, ShawnNew commented on backends/mlu/tools/dockerfile/Dockerfile.mlu.ubuntu18-x86_64-gcc82
> +    wget -O cntoolkit_install_pkg.deb http://daily.software.cambricon.com/release/cntoolkit/Linux/x86_64/Ubuntu/18.04/${CNTOOLKIT_VERSION}/cntoolkit_${CNTOOLKIT_VERSION}.ubuntu18.04_amd64.deb && \
尝试一下用现在开放出去的链接

2023-03-31 02:08 UTC, claire199705 commented on backends/mlu/tools/dockerfile/Dockerfile.mlu.ubuntu18-x86_64-gcc82
> +# install paddlepaddle-cpu whl package
好的

2023-03-31 03:14 UTC, claire199705 commented on backends/mlu/tools/dockerfile/Dockerfile.mlu.ubuntu18-x86_64-gcc82
> +    wget -O cntoolkit_install_pkg.deb http://daily.software.cambricon.com/release/cntoolkit/Linux/x86_64/Ubuntu/18.04/${CNTOOLKIT_VERSION}/cntoolkit_${CNTOOLKIT_VERSION}.ubuntu18.04_amd64.deb && \
好的，已改成sdk下载链接

2023-03-31 03:14 UTC, claire199705 commented on backends/mlu/tools/dockerfile/build-image.sh
> +CNTOOLKIT_VERSION=${1:-3.1.2-1} # default 3.1.2-1
好的，已修改成ctr2.8.1对应组件版本

2023-03-31 03:14 UTC, claire199705 commented on backends/mlu/tools/pr_ci_mlu.sh
> +    retry_time=4
好的，retry_time已改成0

2023-04-03 12:13 UTC, ShawnNew approved these changes
👍

2023-04-03 12:14 UTC, merged