[MLU] add log_softmax
PaddlePaddle/PaddleCustomDevice pull request #490
Opened 2023-04-07 14:01 UTC by Ashelly1

[MLU] add log_softmax

2023-04-07 14:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleCustomDevice?pullRequest=490) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleCustomDevice?pullRequest=490) before we can accept your contribution.<br/><hr/>**liupeiyu** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleCustomDevice?pullRequest=490) it.</sub>

2023-04-13 02:06 UTC, ShawnNew requested changes

2023-04-13 02:06 UTC, ShawnNew commented on backends/mlu/kernels/log_softmax_kernel.cc
> +  if (x.numel() != 0) {
这里不用条件判断

2023-04-13 02:06 UTC, ShawnNew commented on backends/mlu/kernels/log_softmax_kernel.cc
> +  if (dout.numel() != 0) {
同上

2023-04-14 06:09 UTC, Ashelly1 commented on backends/mlu/kernels/log_softmax_kernel.cc
> +  if (x.numel() != 0) {
已修改

2023-04-14 06:09 UTC, Ashelly1 commented on backends/mlu/kernels/log_softmax_kernel.cc
> +  if (dout.numel() != 0) {
已修改

2023-04-14 06:11 UTC, ShawnNew approved these changes
LGTM

2023-04-14 06:34 UTC, merged