[MLU] add coalesce_tensor kernel
PaddlePaddle/PaddleCustomDevice pull request #491
Opened 2023-04-10 02:52 UTC by Ashelly1

add coalesce_tensor kernel

2023-04-10 02:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleCustomDevice?pullRequest=491) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleCustomDevice?pullRequest=491) before we can accept your contribution.<br/><hr/>**liupeiyu** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleCustomDevice?pullRequest=491) it.</sub>

2023-04-10 02:52 UTC, Ashelly1 commented
![image](https://user-images.githubusercontent.com/22099158/230815988-46ef5768-94a8-45f4-85fb-e76f16e20504.png)

2023-04-17 08:25 UTC, ShawnNew requested changes

2023-04-17 08:25 UTC, ShawnNew commented on backends/mlu/kernels/coalesce_tensor_kernel.cc
> +  }
else, set zero

2023-04-17 09:01 UTC, Ashelly1 commented on backends/mlu/kernels/coalesce_tensor_kernel.cc
> +  }
已修改

2023-04-17 09:36 UTC, ShawnNew approved these changes
LGTM

2023-04-17 11:18 UTC, merged