[MLU] fix CrossEntropyWithSoftmaxGradKernel
PaddlePaddle/PaddleCustomDevice pull request #495
Opened 2023-04-12 04:28 UTC by claire199705

2023-04-12 04:54 UTC, ShawnNew requested changes

2023-04-12 04:54 UTC, ShawnNew commented on backends/mlu/kernels/cross_entropy_kernel.cc
> +      // sub
把这段逻辑和上面的sub+mul合并，不用重复写

2023-04-12 06:17 UTC, claire199705 commented on backends/mlu/kernels/cross_entropy_kernel.cc
> +      // sub
已修改

2023-04-13 02:13 UTC, ShawnNew requested changes

2023-04-13 02:13 UTC, ShawnNew commented on backends/mlu/kernels/cross_entropy_kernel.cc
> +    if (!soft_label && labels.numel() == n && ignore_index == -1) {
条件判断之后增加必要注释

2023-04-13 02:13 UTC, ShawnNew commented on backends/mlu/kernels/cross_entropy_kernel.cc
> +      phi::DenseTensor casted_onehot;
casted_onehot直接用last_labels

2023-04-13 02:13 UTC, ShawnNew commented on backends/mlu/kernels/cross_entropy_kernel.cc
> +                      GetBasePtr(&casted_onehot));
同上

2023-04-13 02:13 UTC, ShawnNew commented on backends/mlu/kernels/cross_entropy_kernel.cc
> +      last_labels = labels;
else之后添加必要注释

2023-04-13 03:37 UTC, claire199705 commented on backends/mlu/kernels/cross_entropy_kernel.cc
> +    if (!soft_label && labels.numel() == n && ignore_index == -1) {
已加

2023-04-13 03:37 UTC, claire199705 commented on backends/mlu/kernels/cross_entropy_kernel.cc
> +      phi::DenseTensor casted_onehot;
已改

2023-04-13 03:37 UTC, claire199705 commented on backends/mlu/kernels/cross_entropy_kernel.cc
> +      last_labels = labels;
已加

2023-04-13 03:42 UTC, ShawnNew approved these changes
LGTM

2023-04-13 03:42 UTC, merged