[MLU] add any, add square&square kernel test, fix reduce_op
PaddlePaddle/PaddleCustomDevice pull request #627
Opened 2023-06-14 09:30 UTC by PeiyuLau

2023-06-14 09:32 UTC, PeiyuLau commented
square:
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/135964669/90bb3a64-2578-4fa1-84b2-fae00a1851e9)

2023-06-14 09:41 UTC, PeiyuLau commented
reduce_any:
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/135964669/ec47d916-3f0c-4305-8a12-ea353cc60952)

2023-06-14 09:45 UTC, ShawnNew commented
do not merge after [pr-626](https://github.com/PaddlePaddle/PaddleCustomDevice/pull/626)

2023-06-14 09:57 UTC, ShawnNew requested changes

2023-06-14 09:57 UTC, ShawnNew commented on backends/mlu/kernels/reduce_any_kernel.cc
> +  MLUReduceOp<T>(dev_ctx, x, dim_vec, keep_dim, reduce_all, "reduce_any", out);
the upper logic may included in this function already, minor changes are suggested.

2023-06-15 09:03 UTC, ShawnNew approved these changes
LGTM

2023-06-16 01:46 UTC, merged