[NPU] dynamic batch inference adaptation
PaddlePaddle/PaddleCustomDevice pull request #798
Opened 2023-09-20 09:53 UTC by ShuZihan

2023-09-20 10:17 UTC, ronny1996 requested changes

2023-09-20 10:17 UTC, ronny1996 commented on backends/npu/custom_op/linear_op.cc
>  #include "kernels/funcs/format_utils.h"
注释的代码可以删除

2023-09-20 10:17 UTC, ronny1996 commented on backends/npu/custom_op/llama_decoder_layer_parallel_op.cc
> +  // int32_t layer_num = 80; /* TODO:65B，写死8卡 */
同上

2023-09-20 13:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleCustomDevice?pullRequest=798) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleCustomDevice?pullRequest=798) before we can accept your contribution.<br/>**2** out of **5** committers have signed the CLA.<br/><br/>:white_check_mark: ShuZihan<br/>:white_check_mark: max-niu<br/>:x: MyAngelAyase<br/>:x: yuanwei<br/>:x: bmers<br/><hr/>**yuanwei** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleCustomDevice?pullRequest=798) it.</sub>

2023-10-17 09:22 UTC, bmers commented
0、导出模型
1、安装加速库，声明环境变量
./Ascend-cann-atb_7.0.RC1_cxx11abi1_linux-x86_64.run --install
cd /usr/local/Ascend/atb/
source set_env.sh
2、编译Paddle
https://github.com/MyAngelAyase/Paddle.git
3、编译PaddleCustomdevice
https://github.com/MyAngelAyase/PaddleCustomDevice.git
根据运行模型的大小，修改相关参数
    export WITH_ASCEND_TRANSFORMER_ACC=ON
    bash tools/compile.sh
4、声明动态batch后处理算子路径
export ASCEND_CUSTOM_OPP_PATH=/XXX/PATH
5、使用PaddleNLP：https://github.com/MyAngelAyase/PaddleNLP.git
将PaddleNLP路径设入PYTHONPATH
export PYTHONPATH=/xxx/PaddleNLP:$PYTHONPATH
6、在PaddleNLP路径下执行
bash infer_llama_npu.sh

2023-10-17 09:34 UTC, bmers commented
1、安装加速库，声明环境变量
./Ascend-cann-atb_7.0.RC1_cxx11abi1_linux-x86_64.run --install
cd /usr/local/Ascend/atb/
source set_env.sh
2、编译Paddle
https://github.com/MyAngelAyase/Paddle.git
3、编译PaddleCustomdevice
https://github.com/MyAngelAyase/PaddleCustomDevice.git
根据运行模型的大小，修改相关参数
    export WITH_ASCEND_TRANSFORMER_ACC=ON
    bash tools/compile.sh
4、声明动态batch后处理算子路径
export ASCEND_CUSTOM_OPP_PATH=/XXX/PATH
5、使用PaddleNLP：https://github.com/MyAngelAyase/PaddleNLP.git
将PaddleNLP路径设入PYTHONPATH
export PYTHONPATH=/xxx/PaddleNLP:$PYTHONPATH
6、在PaddleNLP路径下执行
bash infer_llama_npu.sh

2023-10-21 12:44 UTC, qili93 commented
昇腾910B下预测输出结果为空 ，复现步骤如下：

## 一、运行环境

运行机器的驱动和版本信息如下，是CANN 7.0.RC1的配套驱动安装的

```bash
# 获取版本信息
/usr/local/Ascend/toolbox/latest/Ascend-DMI/bin/ascend-dmi -c
# 显示信息如下
|==========================================================================================================|
|                                                System Information                                        |
|==========================================================================================================|
| Architecture        | x86_64                                                                             |
+---------------------+------------------------------------------------------------------------------------+
| Type                | Ascend 910 B2                                                                      |
|==========================================================================================================|
|                                  Compatibility Check Result: Incompatible                                |
|==========================================================================================================|
| Package             | Version           | Status           | Innerversion            | Dependencies      |
+---------------------+-------------------+------------------+-------------------------+-------------------+
| npu-driver          | 23.0.rc3          | OK               | V100R001C30SPC004B220   | NA                |
+---------------------+-------------------+------------------+-------------------------+-------------------+
| npu-firmware        | NA                | NA               | NA                      | NA                |
+---------------------+-------------------+------------------+-------------------------+-------------------+
```

## 二、启动容器

CANN 7.0.RC1的 toolkit/kernels/atb 算子库等都安装在镜像环境中

```bash
# 开发镜像 - 内置 CANN 7.0.RC1
docker run -it --name paddle-cann701-npu -v `pwd`:/workspace \
    -v /home/datasets:/datasets --workdir=/workspace \
    --privileged --network=host --shm-size=128G \
    -v /usr/local/Ascend/driver:/usr/local/Ascend/driver \
    -v /usr/local/bin/npu-smi:/usr/local/bin/npu-smi \
    -v /usr/local/dcmi:/usr/local/dcmi \
    registry.baidubce.com/device/paddle-npu:cann701-ubuntu18-$(uname -m)-gcc82 /bin/bash
```

## 三、安装编译

```bash
# Paddle (5832764483 2023-10-13)
git clone https://github.com/MyAngelAyase/Paddle.git -b develop
cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DPY_VERSION=3.9 -DPYTHON_EXECUTABLE=`which python3` -DWITH_CUSTOM_DEVICE=ON \
  -DWITH_TESTING=OFF -DON_INFER=ON -DWITH_DISTRIBUTE=ON

# PaddleCustomDevice (d18ac10 2023-10-19)
git clone. https://github.com/MyAngelAyase/PaddleCustomDevice.git -b develop
export WITH_ASCEND_TRANSFORMER_ACC=ON
bash tools/compile.sh

# PaddleNLP (be61dcef 2023-09-12)
git clone https://github.com/MyAngelAyase/PaddleNLP.git -b develop
cd PaddleNLP && pip install -e .

# 后处理自定义算子 
wget xxxx/addle_post_processALL.zip
cd build && bash build_ops.sh
bash  aie_ops.run --extract=. # 当前路径下生成vendors目录
# 设置算子库路径
export ASCEND_CUSTOM_OPP_PATH=/xxx/vendors/aie_ascendc
```

## 四、模型导出

```bash
# 注意代码里面的 transformat_weight 被注释了，直接导出问题加载参数有问题，需要启用
# 注意代码最后的 validate_pdmodel 仅会检查单卡输出模型，再多卡模型导出下可以先注释
cd PaddleNLP/llm
python -m paddle.distributed.launch --devices "0,1,2,3,4,5,6,7" export_model.py \
    --model_name_or_path facebook/llama-65b \
    --output_path ./export_llama65b_fp16_mp8 \
    --dtype float16 \
    --inference_model
```

## 五、模型预测

```bash
export ASCEND_RT_VISIBLE_DEVICES="0,1,2,3,4,5,6,7"
export FLAGS_use_stream_safe_cuda_allocator=0
export LCCL_ENABLE_FALLBACK=1
export HCCL_OP_BASE_FFTS_MODE_ENABLE=TRUE
export FLAGS_eager_delete_tensor_gb=-1.0 
export FLAGS_allocator_strategy="auto_growth"
export ASCEND_CUSTOM_OPP_PATH=/workspace/huawei/vendors/aie_ascendc
    
python -m paddle.distributed.launch --devices "0,1,2,3,4,5,6,7" predictor.py \
    --model_name_or_path ./export_llama65b_fp16_mp8 \
    --dtype float16 \
    --src_length 300 \
    --max_length 400 \
    --dtype float16 \
    --output_file "infer.json" \
    --mode "static" \
    --batch_size 1 \
    --inference_model \
    --device "npu"
rm -rf real_time_save*
```

预测输出结果为空，但在A800机器上是有正常输出结果的

```json
{"src": "hello world, how are you?", "tgt": "", "output": ""}
{"src": "你好，请问你是谁?", "tgt": "", "output": ""}
```

2024-03-29 08:50 UTC, closed without merging