[MLU] add kernel flash_attention
PaddlePaddle/PaddleCustomDevice pull request #802
Opened 2023-09-22 03:19 UTC by cifar10

1、添加flash attention前项算子。
2、第一阶段验证方法：
（1）从gpu处保存输入到_C_ops.flash_attn( ) 中的query、key、value值；保存经过_C_ops.flash_attn( )后输出的result_attention值。
（2）将gpu的输入值传入mlu的_C_ops.flash_attn( ) 处，mlu输出结果与gpu的diff如下。
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/41565156/fcd6ef97-7d50-4354-a8de-db4fab90ca3d)

2023-09-22 10:02 UTC, ShawnNew commented on backends/mlu/kernels/flash_attn_kernel.cc
> +  out->Resize({batch_size, total_q/batch_size, num_heads, head_size});
加一个TODO，说明现在只支持等长输入，变长还需要拆分处理

2023-09-27 08:03 UTC, ShawnNew commented on backends/mlu/kernels/flash_attn_kernel.cc
> +                                 GetBasePtr(&softmax_lse_nl),
看看是不是用`softmax_lse`

2023-09-27 08:03 UTC, ShawnNew commented on backends/mlu/kernels/flash_attn_kernel.cc
> +  dev_ctx.template Alloc<float>(&softmax_lse_nl);
这里定义要固定位float吗？

2023-09-27 08:03 UTC, ShawnNew commented on backends/mlu/kernels/flash_attn_kernel.cc
> +void GetSize(T start, T end, T step, int64_t* size) {
`GetSize`函数和range_kernel实现的定义重复，可以抽出来作为公共方法，放在`mlu_funcs.h`

2023-10-07 10:12 UTC, cifar10 commented on backends/mlu/kernels/flash_attn_kernel.cc
> +  out->Resize({batch_size, total_q/batch_size, num_heads, head_size});
已修改。

2023-10-07 10:13 UTC, cifar10 commented on backends/mlu/kernels/flash_attn_kernel.cc
> +                                 GetBasePtr(&softmax_lse_nl),
重新修改和使用softmax_lse，整网训练loss正常。修改前，反向loss中出现nan。

2023-10-07 10:16 UTC, cifar10 commented on backends/mlu/kernels/flash_attn_kernel.cc
> +  dev_ctx.template Alloc<float>(&softmax_lse_nl);
已确认。根据头文件extra.h中约束，Data types of  softmax_lse must be float.
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/41565156/2277836e-bf66-48ab-bc37-e72ef614a7aa)

2023-10-07 10:18 UTC, cifar10 commented on backends/mlu/kernels/flash_attn_kernel.cc
> +void GetSize(T start, T end, T step, int64_t* size) {
已修改完成。range_kernel和flash_atten中的GetSize函数已迁移至mlu_funcs.h。

2023-10-17 09:07 UTC, ShawnNew approved these changes
LGTM

2023-10-17 09:21 UTC, ShawnNew requested changes

2023-10-17 09:21 UTC, ShawnNew commented on backends/mlu/tools/dockerfile/Dockerfile.mlu.ubuntu18.x86_64.gcc82
> +    wget -O cnnlextra_install_pkg.deb ftp://download.cambricon.com:8821/tmp/CTR2.9.0/cnnlextra_${CNNL_EXTRA_VERSION}.ubuntu18.04_amd64.deb --ftp-user=${FTP_USER} --ftp-password=${FTP_PASSWORD} && \
/tmp/cnnlextra目录

2023-10-18 03:31 UTC, ShawnNew approved these changes

2023-10-18 06:08 UTC, merged