[MLU] add swish and swish_grad kernel
PaddlePaddle/PaddleCustomDevice pull request #803
Opened 2023-09-26 09:18 UTC by PeiyuLau

add swish and swish_grad kernel

2023-09-27 07:28 UTC, ShawnNew requested changes

2023-09-27 07:28 UTC, ShawnNew commented on backends/mlu/kernels/activation_kernel.cc
> +  ActivationKernel<T, Context>(dev_ctx, x, 1.0, CNNL_ACTIVATION_SILU, out);
magic number？

2023-09-27 07:28 UTC, ShawnNew commented on backends/mlu/tests/unittests/test_swish_op_mlu.py
> +# class TestCase3(TestSwish):
为什么注释？如果没有可以删除

2023-09-27 07:57 UTC, PeiyuLau commented on backends/mlu/kernels/activation_kernel.cc
> +  ActivationKernel<T, Context>(dev_ctx, x, 1.0, CNNL_ACTIVATION_SILU, out);
1.0 是 ceof , 只有在设置了相关的激活函数模式才会用到。

2023-09-27 07:57 UTC, PeiyuLau commented on backends/mlu/tests/unittests/test_swish_op_mlu.py
> +# class TestCase3(TestSwish):
数据规模增大，反向速度太慢，可能某些规模下存在问题。

2023-09-27 08:53 UTC, ShawnNew commented on backends/mlu/kernels/activation_kernel.cc
> +  ActivationKernel<T, Context>(dev_ctx, x, 1.0, CNNL_ACTIVATION_SILU, out);
用`/* ceof */`标注一下

2023-09-27 08:54 UTC, ShawnNew commented on backends/mlu/tests/unittests/test_swish_op_mlu.py
> +# class TestCase3(TestSwish):
这里应该直接调用的cnnl算子，性能问题先和nl确认一下

2023-09-28 02:08 UTC, PeiyuLau commented on backends/mlu/kernels/activation_kernel.cc
> +  ActivationKernel<T, Context>(dev_ctx, x, 1.0, CNNL_ACTIVATION_SILU, out);
已修改

2023-10-08 09:54 UTC, ShawnNew commented on backends/mlu/tests/unittests/test_swish_op_mlu.py
> +# class TestCase3(TestSwish):
保留TestCase3，调整规模为[4, 1, 15, 15]

2023-10-09 11:14 UTC, PeiyuLau commented on backends/mlu/tests/unittests/test_swish_op_mlu.py
> +# class TestCase3(TestSwish):
经测试，cnnl 算子性能正常。耗时主要是在测例在计算梯度时 for 循环次数太大。
![{707b6ffc-9631-403c-993b-b3cac4347ca4}](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/135964669/7829403a-44d6-42c9-98a0-077a20e8875a)

2023-10-09 11:19 UTC, ShawnNew commented on backends/mlu/kernels/tril_triu_op_mlu.cc
> +  dev_ctx.template Alloc<int>(&x_tensor);
分配内存可以写在if分支里边，如果走到else的话可以避免多一次alloc操作

2023-10-10 06:16 UTC, ShawnNew requested changes

2023-10-10 06:16 UTC, ShawnNew commented on backends/mlu/kernels/warpctc_kernel.cc
> +  *logits_grad = warpctcgrad;
这两个量应该不能直接等，梳理一下计算逻辑

2023-10-10 07:21 UTC, PeiyuLau commented on backends/mlu/kernels/tril_triu_op_mlu.cc
> +  dev_ctx.template Alloc<int>(&x_tensor);
已修改

2023-10-10 07:22 UTC, PeiyuLau commented on backends/mlu/kernels/warpctc_kernel.cc
> +  *logits_grad = warpctcgrad;
梳理中

2023-10-10 11:17 UTC, ShawnNew approved these changes
LGTM

2023-10-10 11:17 UTC, merged