[CI] disable some unit test
PaddlePaddle/PaddleCustomDevice pull request #875
Opened 2024-01-02 12:13 UTC by xysheng-baidu

[CI] disable some unit test

2024-01-02 12:42 UTC, qili93 requested changes
请参考 910A 的 CI 流水线 https://xly.bce.baidu.com/paddlepaddle/paddle-custom-device/newipipe/detail/9856317/job/24951025 中通过的单测用例，910A上原有的 disable_ut_npu 以外的单侧用例都可以通过，910A可以通过的默认就不disable，建议要么910B单独维护一个独立的 disable_ut_npu 文件，要么尽量修复单侧挂之后再提PR，谢谢！

2024-01-08 03:08 UTC, xysheng-baidu commented
> 请参考 910A 的 CI 流水线 https://xly.bce.baidu.com/paddlepaddle/paddle-custom-device/newipipe/detail/9856317/job/24951025 中通过的单测用例，910A上原有的 disable_ut_npu 以外的单侧用例都可以通过，910A可以通过的默认就不disable，建议要么910B单独维护一个独立的 disable_ut_npu 文件，要么尽量修复单侧挂之后再提PR，谢谢！

目前910B单独维护了disable_ut_npu，不过在没有修改代码的情况下，910A的CI过不去，目前910A的CI是可用的吗？

2024-01-08 12:35 UTC, qili93 commented on backends/npu/tools/pr_ci_npu.sh
> +    fi
这里的逻辑建议可以参考 https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/tools/dockerfile/build-image.sh#L39 进行判断机器环境

```
if [ $(lspci | grep d801 | wc -l) -ne 0 ]; then
  disable_ut_npu=$(cat "${CODE_ROOT}/tools/disable_ut_npu")
elif [ $(lspci | grep d802 | wc -l) -ne 0 ]; then
  disable_ut_npu=$(cat "${CODE_ROOT}/tools/disable_ut_npu_910b")
else
  echo "Please make sure Ascend 910A or 910B NPUs exists!"
  exit 1
fi
```

这样就不需要新增 USE_910B 的环境变量

2024-01-08 13:01 UTC, xysheng-baidu commented on backends/npu/tools/pr_ci_npu.sh
> +    fi
已修改。

2024-01-09 02:35 UTC, qili93 approved these changes
LGTM

2024-01-09 02:35 UTC, merged

2024-01-21 15:16 UTC, Tongkaio commented on backends/npu/kernels/funcs/npu_enforce.h
请问一下这里为什么要修改，我编译时因为这里的变化出现了错误：
<img width="1119" alt="image" src="https://github.com/PaddlePaddle/PaddleCustomDevice/assets/104260574/f7fc38fc-870b-45bf-a03a-29746f3ff3f0">