add aclnn call for abs operator as an example
PaddlePaddle/PaddleCustomDevice pull request #877
Opened 2024-01-04 03:40 UTC by zhenwenqi2024

(1)add aclnn call marco
(2)abs example for aclnn call

2024-01-04 03:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleCustomDevice?pullRequest=877) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleCustomDevice?pullRequest=877) before we can accept your contribution.<br/><hr/>**matrixssy** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleCustomDevice?pullRequest=877) it.</sub>

2024-01-04 07:37 UTC, qili93 requested changes

2024-01-04 07:37 UTC, qili93 commented on backends/npu/kernels/abs_kernel.cc
> +    EXEC_NPU_CMD(aclnnAbs, size, dev_ctx, x, *out);
不要直接删除原有的aclops的代码，建议修改为

1. 默认走 aclnn，然后让 aclnn 执行成功之后直接返回就走不到aclop的代码了；
2. 如果aclnn执行失败或者找不到aclnn的库，就继续走原有的aclop的执行逻辑；

这样能保证在CANN 6.0.1或者更早的不支持aclnn的版本上也能保证Paddle+NPU可以正常运行。

2024-01-04 12:21 UTC, zhenwenqi2024 commented on backends/npu/kernels/abs_kernel.cc
> +    EXEC_NPU_CMD(aclnnAbs, size, dev_ctx, x, *out);
已修改，兼容性增强，aclnn走不通的时候默认走aclop请检视。

2024-01-05 06:48 UTC, gongweibao requested changes

2024-01-05 06:48 UTC, gongweibao commented on backends/npu/kernels/abs_kernel.cc
> +void AbsKernelOp(const Context& dev_ctx,
It's a function, not an OP.  Maybe`aclAbsKernel` is better?

2024-01-05 06:48 UTC, gongweibao commented on backends/npu/kernels/abs_kernel.cc
> +void AbsGradKernelOp(const Context& dev_ctx,
Same as above.

2024-01-05 06:48 UTC, gongweibao commented on backends/npu/kernels/funcs/npu_op_runner.h
> +  if (custOpApiHandler != nullptr) {
Add some comments

2024-01-05 06:54 UTC, gongweibao requested changes
Desciption要写清楚：
做了什么，有什么效果。可以写中文。

2024-01-05 07:11 UTC, zhenwenqi2024 commented on backends/npu/kernels/abs_kernel.cc
> +void AbsGradKernelOp(const Context& dev_ctx,
AclopAbsGradKernel

2024-01-05 11:57 UTC, closed without merging