support bf16
PaddlePaddle/PaddleCustomDevice pull request #887
Opened 2024-01-11 12:38 UTC by tianhaodongbd

2024-01-28 03:11 UTC, gongweibao requested changes
https://github.com/PaddlePaddle/Paddle/pull/60768/files 这个PR没有合入为何单测都过了。

2024-02-02 01:31 UTC, gongweibao commented on backends/npu/tests/unittests/npu_utils.py
> +            paddle_custom_device.npu.version()["cann"].split(".")[0] == "7"
int(version) >= 7

2024-02-02 04:49 UTC, tianhaodongbd commented on backends/npu/tests/unittests/npu_utils.py
> +            paddle_custom_device.npu.version()["cann"].split(".")[0] == "7"
done

2024-02-04 02:25 UTC, gongweibao approved these changes
LGTM

2024-02-04 02:25 UTC, merged