[MLU] Add cpu_allocator notifier protect and utilize hostmalloc for a…
PaddlePaddle/PaddleCustomDevice pull request #982
Opened 2024-03-05 09:22 UTC by PeiyuLau

Add cpu_allocator notifier protect and utilize hostmalloc for asynH2D acceleration

2024-03-05 11:32 UTC, ShawnNew requested changes

2024-03-05 11:32 UTC, ShawnNew commented on backends/mlu/kernels/funcs/mlu_funcs.h
> +      C_Device_st device{dst_place_.GetDeviceId()};
1. move this variable before if branch for code simplification
2. add all devices

2024-03-05 13:09 UTC, PeiyuLau commented on backends/mlu/kernels/funcs/mlu_funcs.h
> +      C_Device_st device{dst_place_.GetDeviceId()};
done

2024-03-06 02:10 UTC, ShawnNew approved these changes
LGTM

2024-03-06 12:35 UTC, ronny1996 approved these changes
LGTM

2024-03-07 12:01 UTC, merged